pull_request_rules:
  - name: automatic merge with strict
#     conditions:
#       - author=introproventures-jenkins-x
#       - status-success=continuous-integration/jenkins/pr-head
    actions:
      delete_head_branch: {}
      merge:
        method: merge
        strict: true
