pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - author=almerico
      - status-success=continuous-integration/jenkins/pr-head
    actions:
      delete_head_branch: {}
      merge:
        method: merge
        strict: true