pull_request_rules:
  - name: automatic merge for Dependabot pull requests on master
    conditions:
      - author=almerico
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: merge
